import { ICONS } from './icons.js';
import { safeUrl } from './verification.js';
export const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
export const icon = name => (ICONS[name] || ICONS.document).replace('<svg ', '<svg aria-hidden="true" focusable="false" ');
export const logo = () => '<span class="logo-art" role="img" aria-label="سابر"></span>';
export function header(home = false) { return `<header class="header"><div class="nav-shell"><a class="brand" href="/" aria-label="سابر — الرئيسية">${logo()}</a><button class="menu-toggle" aria-label="فتح القائمة" aria-expanded="false">☰</button><nav aria-label="القائمة الرئيسية"><a href="/#how-it-works">كيف يعمل</a><a href="/#about">من نحن</a><a href="/#trending">الأخبار الشائعة</a><a href="/saved">الأخبار المحفوظة</a></nav><div class="nav-actions"><a href="/login">تسجيل الدخول</a>${home ? '<a class="button small" href="/signup">ابدأ مجاناً ←</a>' : ''}</div></div></header>`; }
export function footer() { return `<footer class="footer"><div class="footer-inner"><div class="footer-about"><a href="/" class="footer-brand">${logo()}<span>سابر</span></a><p>منصة سعودية رائدة في تقنيات<br>الذكاء الاصطناعي لتحليل المحتوى<br>والتحقق من الحقائق<br>لضمان فضاء رقمي موثوق</p></div><div><h3>حساباتنا</h3><span class="social-line"><b class="linkedin">in</b> منصة لينكدإن</span><span class="social-line"><b>𝕏</b> منصة اكس</span></div><nav aria-label="روابط التذييل"><a href="/#how-it-works">كيف يعمل سابر</a><a href="/#about">من نحن</a><a href="/#trending">الأخبار الشائعة</a></nav></div></footer>`; }
export function newsCard(item, { saved = false, index = 0 } = {}) { return `<article class="news-card"><div class="news-copy"><div class="news-meta"><span class="badge tone-${index % 3}">${saved ? '938 مرة' : `${icon('check')} ${esc(item.match_score ?? '—')}% تطابق`}</span>${!saved ? `<span>${icon('calendar')} ${esc(item.news_date || '')}</span>` : ''}</div><h3>${esc(item.title)}</h3><p>${esc(item.explanation)}</p><span class="source-caption">${icon('newspaper')} ${esc(item.source_name)}</span></div><div class="news-actions"><button class="button ${index === 0 || saved ? 'dark' : 'quiet'}" data-select="${esc(item.id)}">${saved ? 'المزيد' : 'اختيار هذا الخبر'} ${icon('arrowLeft')}</button>${saved ? `<button class="button quiet" data-unsave="${esc(item.id)}">إلغاء حفظ الخبر ${icon('bookmark')}</button>` : ''}</div></article>`; }
export function sourceCard(source) { const url = safeUrl(source.url); return `<article class="source-card"><div class="source-card-top"><span class="round-icon">${icon('newspaper')}</span><span class="badge green">${['official','government'].includes(source.tier) ? 'موثوق ✓' : 'مصدر'}</span></div><h3>${esc(source.name)}</h3><p>${source.tier === 'official' ? 'مصدر رسمي' : source.tier === 'government' ? 'جهة حكومية' : 'مصدر إعلامي'}</p>${url ? `<a class="source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">عرض المصدر ${icon('link')}</a>` : '<span class="source-link unavailable">الرابط غير متاح</span>'}</article>`; }
export function relatedCard(item) { const url = safeUrl(item.source_url); return `<article class="related-card"><div class="news-meta"><span class="badge blue">تطابق ${esc(item.match_score ?? '—')}%</span><span>${esc(item.news_date || '')}</span></div><h3>${esc(item.title)}</h3><p>${esc(item.explanation)}</p><div class="related-bottom"><span>${icon('newspaper')} ${esc(item.source_name)}</span>${url ? `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">عرض الخبر</a>` : ''}</div></article>`; }
