import '@fontsource/tajawal/arabic-400.css';
import '@fontsource/tajawal/arabic-500.css';
import '@fontsource/tajawal/arabic-700.css';
import '@fontsource/tajawal/arabic-800.css';
import './style.css';
import { header, footer, logo, icon, esc, newsCard, sourceCard, relatedCard } from './components.js';
import { verifyClaim, normalizeVerification, demoMode } from './verification.js';
import { candidates, fixture, sampleInput, exampleTitle } from './fixtures.js';

const app = document.querySelector('#app');
const storage = {
  get(key, fallback) { try { return JSON.parse(sessionStorage.getItem(key)) ?? fallback; } catch { return fallback; } },
  set(key, value) { try { sessionStorage.setItem(key, JSON.stringify(value)); } catch { /* Session persistence is optional. */ } }
};
let lastInput = storage.get('saber:input', '');
let result = storage.get('saber:result', null);
let savedNews = storage.get('saber:saved', demoMode ? candidates : []);
let controller;
let feedback = null;
function toast(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('visible'), 4500); }
function navigate(path) { history.pushState({}, '', path); render(); window.scrollTo({ top: 0 }); }
const demoNote = () => demoMode ? '<p class="demo-note">نسخة تجريبية — النتائج المعروضة للتوضيح وليست تحققاً فعلياً.</p>' : '';
function home() { return `<section class="hero"><div class="hero-inner"><div class="hero-copy"><h1>اليقين الرقمي<br><span>في عصر<br>الشائعات</span></h1><p>منصة سعودية مدعومة بالذكاء الاصطناعي لتحليل الادعاءات،<br>كشف التضليل، وتقديم مصادر بضغطة واحدة. لا تدع الأخبار<br>الزائفة تخدعك.</p><a href="/verify" class="button">ابدأ التحقق</a></div><div class="hero-art" role="img" aria-label="عدسة سابر للتحقق من الأخبار وتحليلها"></div></div></section>
<section id="how-it-works" class="how-section"><h2>كيف يعمل سابر؟</h2><div class="timeline">${[
['الخطوة الأولى','أدخل الادعاء أو ألصق الرابط','انسخ الخبر، التغريدة، أو أي محتوى مشكوك فيه وألصقه في مربع التحقق الذكي.','document'],
['الخطوة الثانية','تحليل الذكاء الاصطناعي','تبدأ خوارزمياتنا بالعمل في الخلفية، تقارن عدداً من المصادر الرسمية.','brain'],
['الخطوة الثالثة','عرض النتيجة والأدلة','ستحصل على تقرير مفصل يشمل نسبة المصداقية، المصادر الأصلية، تفسير منطقي واضح، وإمكانية مشاركة التقرير.','documentCheck']
].map(([step,title,text,i],n)=>`<article class="step step-${n}"><span class="step-icon">${icon(i)}</span><div><span class="step-label">${step}</span><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div></section>
<section id="about" class="about-section"><h2>من نحن</h2><div class="about-grid"><article><h3>نجعل الوصول إلى<br>الحقيقة أسرع وأكثر<br>موثوقية.</h3><p>سابر منصة سعودية تستخدم الذكاء الاصطناعي للتحقق من الأخبار وكشف المعلومات المضللة، عبر مقارنة المحتوى بالمصادر الرسمية وتحليل موثوقيته بدقة وشفافية.</p><p>حصد فريق سابر المركز الأول في معسكر الابتكار الإعلامي ضمن مسار الصحافة المعززة بالذكاء الاصطناعي، في إنجاز يعكس رؤيتنا لتطوير حلول تقنية تدعم الإعلام الموثوق وتعزز الوعي الرقمي.</p></article><div class="team-art" role="img" aria-label="فريق سابر يتسلم جائزة معسكر الابتكار الإعلامي"></div></div></section>
<section id="trending" class="trending-section"><div class="section-top"><h2>ادعاءات يتداولها الناس</h2><a href="/news">عرض جميع الادعاءات</a></div><div class="claims-grid">${[0,1,2].map(()=>`<article class="claim-card"><div class="claim-status">${icon('circleInfo')}<div><small>الصحة</small><strong>مضلل</strong></div></div><p>"الليمون يقضي على السرطان وهو أقوى من العلاج الكيماوي"</p><div class="score-label"><span>نسبة الموثوقية</span><b>8%</b></div><div class="tiny-meter"><span></span></div><div class="claim-bottom"><span>مثال توضيحي</span><a href="/result?demo=rumor">قراءة التقرير</a></div></article>`).join('')}</div></section>`; }
function verifyPage() { return `<section class="verify-page"><div class="page-heading"><h1>تحقق من الخبر</h1><p>ألصق الخبر أو رابط الخبر وسيقوم الذكاء الاصطناعي بتحليل المصداقية وإظهار الأدلة<br>والمصادر خلال ثوانٍ.</p></div><form id="verify-form" class="verify-form"><label class="sr-only" for="claim">نص الخبر أو رابط الخبر</label><textarea id="claim" name="claim" maxlength="10000" placeholder="اكتب الخبر هنا أو الصق النص بالكامل..." required>${esc(lastInput)}</textarea><p id="form-error" class="form-error" role="alert"></p><button class="button verify-button" type="submit">تحقق الآن</button><div class="loading-message" role="status" aria-live="polite"></div></form><p class="privacy-note">${icon('shield')} خصوصيتك مهمة. أدخل فقط المعلومات اللازمة للتحقق.</p>${demoNote()}</section>`; }
function clarification(suggested = false) { const current = result?.status === 'no_match' || result?.status === 'suggested' ? result : normalizeVerification(fixture('no_match', sampleInput), sampleInput, true); const items = current.similarNews; return `<section class="clarification"><div class="clarification-intro"><h1>${suggested ? 'أخبار مقترحة تطابق بحثك' : 'لم نتمكن من تحديد الخبر المقصود'}</h1><p>${esc(current.explanation)}</p><strong>ساعدنا بتحديد الخبر الصحيح لنتمكن من بدء عملية التحقق.</strong><article class="quote-card"><h3>${icon('chat')} النص الذي أدخلته</h3><blockquote>${esc(current.title || lastInput || sampleInput)}</blockquote><p>${icon('circleInfo')} قد تختلف صياغة الخبر عن الصياغة المنشورة في المصادر الرسمية.</p></article></div><div class="news-list"><h2>${icon('edit')} هل تقصد أحد هذه الأخبار؟</h2>${items.length ? items.map((item,index) => newsCard(item,{ index })).join('') : '<p class="empty">لا توجد أخبار مقترحة. جرّب إضافة تفاصيل أو رابط المصدر.</p>'}<div class="clarification-bottom"><article><h3>لم تجد الخبر الذي تقصده؟</h3><div><a href="/verify" class="button quiet">${icon('edit')} تعديل النص</a><a href="/verify?mode=url" class="button quiet">${icon('link')} إدخال رابط الخبر</a></div></article><article class="tip"><span class="round-icon">${icon('bulb')}</span><div><h3>نصيحة للحصول على نتائج أفضل</h3><p>كلما كانت صياغة الخبر أوضح أو تم إرفاق الرابط الأصلي، أصبحت نتائج التحقق أكثر دقة وسرعة.</p></div></article></div>${demoNote()}</div></section>`; }
function savedPage() { return `<section class="saved-page"><div class="saved-heading"><h1>الأخبار المحفوظة</h1></div><div class="news-list">${demoMode ? '<p class="demo-note">قائمة تجريبية محفوظة لهذه الجلسة فقط.</p>' : ''}${savedNews.length ? savedNews.map((item,index)=>newsCard(item,{saved:true,index})).join('') : '<div class="empty"><h2>لا توجد أخبار محفوظة بعد</h2><p>يمكنك حفظ تقرير التحقق للرجوع إليه خلال هذه الجلسة.</p><a href="/verify" class="button">ابدأ التحقق</a></div>'}</div></section>`; }
function resultPage() {
  const preview = new URLSearchParams(location.search).get('demo');
  const report = preview && demoMode ? normalizeVerification(fixture(preview),exampleTitle,true) : result;
  if (!report) return `<section class="empty"><h1>ابدأ بالتحقق من خبر</h1><p>ستظهر النتيجة هنا بعد إدخال الخبر وتحليله.</p><a class="button" href="/verify">ابدأ التحقق</a></section>`;
  if (report.status === 'no_match' || report.status === 'suggested') return clarification(report.status === 'suggested');
  if (report.status === 'error') return `<section class="empty error-page"><span class="round-icon">${icon('circleInfo')}</span><h1>${esc(report.statusTitle)}</h1><p>${esc(report.explanation)}</p><a href="/verify" class="button">المحاولة مرة أخرى</a>${report.isDemo ? demoNote() : ''}</section>`;
  const verified = report.status === 'verified';
  return `<div class="result-page" style="--result-color:${report.color}"><section class="result-hero"><div class="result-heading"><span class="badge complete">● عملية التحقق مكتملة</span><h1>${verified ? 'تم التحقق من الخبر' : esc(report.statusTitle)}</h1><p>${verified ? 'أكمل الذكاء الاصطناعي عملية التحقق، وتبين أن الخبر صحيح ومتوافق مع المصادر الرسمية والموثوقة.' : report.status === 'rumor' ? 'أظهرت نتيجة التحقق أن الادعاء غير صحيح وفقاً للأدلة المتاحة.' : 'لم تتوفر أدلة كافية لتأكيد صحة الخبر أو نفيه.'}</p>${report.isDemo ? demoNote() : ''}</div><article class="report-card"><aside><h2>${verified ? 'خبر صحيح وموثوق' : esc(report.statusTitle)}</h2><div class="confidence" style="--score:${report.confidenceScore ?? 0}"><div><strong>${report.confidenceScore === null ? '—' : report.confidenceScore + '%'}</strong><span>${verified ? 'درجة الموثوقية' : 'ثقة نتيجة التحقق'}</span></div></div></aside><div class="report-details"><h3>تفاصيل الخبر المدخل</h3><h2>${esc(report.title)}</h2><p>${esc(report.explanation)}</p><div class="report-meta"><span>${icon('calendar')} تاريخ النشر: ${esc(report.newsDate || 'غير متاح')}</span><span>${icon('user')} ${esc(report.sources[0]?.name || 'لم يُحدد مصدر')}</span><span class="checked">${icon('circleInfo')} تم التحقق بواسطة الذكاء الاصطناعي</span></div>${report.recommendedAction ? `<div class="recommendation"><strong>الإجراء الموصى به</strong><p>${esc(report.recommendedAction)}</p></div>` : ''}</div></article></section><section class="result-evidence"><div class="wide-container"><h2>${icon('bookmark')} المصادر المعتمدة</h2><div class="sources-grid">${report.sources.length ? report.sources.map(sourceCard).join('') : '<p class="empty-source">لم تتوفر مصادر موثوقة كافية لهذا الخبر.</p>'}</div>${report.similarNews.length ? `<h2 class="related-heading">${icon('document')} أخبار مشابهة</h2><div class="related-grid">${report.similarNews.map(relatedCard).join('')}</div>` : ''}</div></section><section class="feedback-section"><div class="feedback-card"><span class="round-icon">${icon('chat')}</span><h2>هل ساعدتك هذه النتيجة؟</h2><p>${feedback ? 'شكراً لك. تم تسجيل رأيك لهذه الجلسة.' : 'رأيك يساعدنا في تحسين تجربة التحقق باستمرار.'}</p><div class="feedback-buttons"><button class="button positive" data-feedback="yes" ${feedback ? 'disabled' : ''}>${icon('thumbsUp')} النتيجة صحيحة</button><button class="button quiet" data-feedback="no" ${feedback ? 'disabled' : ''}>${icon('flag')} أعتقد أن هناك خطأ</button></div><div class="report-tools"><button data-save-report>${icon('bookmark')} حفظ الخبر</button><a href="/verify">تحقق من خبر آخر ←</a></div></div></section></div>`;
}
function field(name, placeholder, type, glyph, extra = '') { return `<label class="field"><span class="sr-only">${placeholder}</span>${icon(glyph)}<input name="${name}" type="${type}" placeholder="${placeholder}" required ${extra}>${name === 'password' ? `<button type="button" class="toggle-password" aria-label="إظهار كلمة المرور">${icon('eye')}</button>` : ''}</label>`; }
function authPage(signup) { return `<section class="auth-layout ${signup ? 'signup' : 'login'}"><div class="auth-form-side"><form id="auth-form" class="auth-card">${signup ? '<h1>إنشاء حساب جديد</h1><p class="auth-subtitle">انضم إلى سابر وابدأ التحقق من الأخبار والمحتوى بدقة وموثوقية</p>' : `<div class="auth-logo">${logo()}<strong>سابر</strong></div><h1>مرحباً بك مجدداً</h1><p class="auth-subtitle">سجل دخولك للوصول إلى حسابك</p>`}${signup ? `<div class="name-fields">${field('firstName','الاسم الأول','text','user','autocomplete="given-name"')}${field('lastName','اسم العائلة','text','user','autocomplete="family-name"')}</div>` : ''}${field('email','البريد الإلكتروني','email','mail','autocomplete="email"')}${field('password','كلمة المرور','password','lock',`minlength="8" autocomplete="${signup ? 'new-password' : 'current-password'}"`)}${signup ? `${field('confirm','تأكيد كلمة المرور','password','lock','autocomplete="new-password"')}<div class="password-rules"><p>كلمة المرور يجب أن تحتوي على:</p><span data-rule="length">${icon('check')} 8 أحرف على الأقل</span><span data-rule="case">${icon('check')} حرف كبير وحرف صغير</span><span data-rule="number">${icon('check')} رقم واحد على الأقل</span></div><label class="checkbox-line"><input type="checkbox" name="terms" required><span>أوافق على <button type="button" class="text-button" data-terms>الشروط والأحكام وسياسة الخصوصية</button></span></label>` : '<div class="auth-options"><label class="checkbox-line"><input type="checkbox" name="remember"> تذكرني</label><button type="button" class="text-button" data-unavailable>نسيت كلمة المرور؟</button></div>'}<p id="auth-message" class="form-error" role="status"></p><button class="button auth-submit" type="submit">${signup ? 'إنشاء حساب' : 'تسجيل دخول'}</button><div class="divider"><span>أو</span></div>${signup ? `<button type="button" class="button google-button" data-unavailable>${icon('google')} إنشاء حساب باستخدام Google</button>` : ''}<p class="auth-switch">${signup ? 'لديك حساب بالفعل؟ <a href="/login">تسجيل الدخول</a>' : 'لا تملك حساباً؟ <a href="/signup">إنشاء حساب جديد</a>'}</p></form></div><div class="auth-art ${signup ? 'signup-art' : 'login-art'}" role="img" aria-label="تحقق من الأخبار، بذكاء وموثوقية. سابر منصة سعودية للتحقق من الأخبار والمحتوى."></div></section>`; }
function render() {
  controller?.abort(); controller = null;
  const path = location.pathname.replace(/\.html$/, '').replace(/\/$/, '') || '/';
  let body; let title;
  switch(path) {
    case '/': case '/index': body = home(); title='اليقين الرقمي'; break;
    case '/verify': body=verifyPage(); title='تحقق من الخبر'; break;
    case '/login': body=authPage(false); title='تسجيل الدخول'; break;
    case '/signup': body=authPage(true); title='إنشاء حساب'; break;
    case '/saved': body=savedPage(); title='الأخبار المحفوظة'; break;
    case '/no-match': body=clarification(); title='تحديد الخبر المقصود'; break;
    case '/suggestions': body=clarification(true); title='أخبار مقترحة'; break;
    case '/result': body=resultPage(); title='نتيجة التحقق'; break;
    case '/news': body=`<section class="saved-page"><div class="saved-heading"><h1>ادعاءات يتداولها الناس</h1></div><div class="news-list">${demoNote()}${candidates.map((x,index)=>newsCard(x,{index})).join('')}</div></section>`; title='الأخبار الشائعة'; break;
    default: body='<section class="empty"><h1>الصفحة غير موجودة</h1><a class="button" href="/">العودة للرئيسية</a></section>'; title='الصفحة غير موجودة';
  }
  document.title=`${title} | سابر`;
  app.innerHTML=header(path==='/' || path==='/index')+`<main id="main" tabindex="-1">${body}</main>`+footer();
  bind();
  if (location.hash) requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView());
  if (path==='/verify' && location.search.includes('mode=url')) { const input=document.querySelector('#claim'); input.placeholder='ألصق رابط الخبر الأصلي هنا...'; input.focus(); }
}
async function runVerification(input) {
  controller?.abort(); controller=new AbortController(); const active=controller;
  try {
    lastInput=input; storage.set('saber:input',input);
    result=await verifyClaim(input,{signal:active.signal}); storage.set('saber:result',result); feedback=null;
    if (!active.signal.aborted) navigate(result.status==='no_match' ? '/no-match' : result.status==='suggested' ? '/suggestions' : '/result');
  } catch(error) {
    if(error.name==='AbortError') return;
    const errorEl=document.querySelector('#form-error'); if(errorEl) errorEl.textContent=error.message; else toast(error.message);
    document.querySelectorAll('button[disabled]').forEach(x=>x.disabled=false);
    const button=document.querySelector('.verify-button'); if(button) button.textContent='تحقق الآن';
    const loading=document.querySelector('.loading-message'); if(loading) loading.textContent='';
    document.querySelector('#verify-form')?.setAttribute('aria-busy','false');
  }
}
function bind() {
  document.querySelector('.menu-toggle')?.addEventListener('click',event=>{const expanded=event.currentTarget.getAttribute('aria-expanded')==='true';event.currentTarget.setAttribute('aria-expanded',String(!expanded));document.querySelector('.header').classList.toggle('menu-open',!expanded);});
  document.querySelector('#verify-form')?.addEventListener('submit',event=>{event.preventDefault();const input=event.currentTarget.claim.value.trim();if(!input){document.querySelector('#form-error').textContent='الرجاء كتابة نص الخبر أو إدخال رابطه أولاً.';return;}document.querySelector('#form-error').textContent='';event.currentTarget.setAttribute('aria-busy','true');const button=document.querySelector('.verify-button');button.disabled=true;button.innerHTML='<span class="spinner"></span> جارٍ التحقق...';document.querySelector('.loading-message').textContent='جارٍ تحليل الخبر ومراجعة المصادر، يرجى الانتظار.';runVerification(input);});
  document.querySelectorAll('[data-select]').forEach(button=>button.addEventListener('click',()=>{const item=[...(result?.similarNews || []),...savedNews,...candidates].find(x=>x.id===button.dataset.select);if(item?.report){result=item.report;storage.set('saber:result',result);navigate('/result');return;}if(item){button.disabled=true;button.textContent='جارٍ التحقق...';runVerification(item.title);}}));
  document.querySelectorAll('[data-unsave]').forEach(button=>button.addEventListener('click',()=>{savedNews=savedNews.filter(x=>x.id!==button.dataset.unsave);storage.set('saber:saved',savedNews);render();toast('تم إلغاء حفظ الخبر.');}));
  document.querySelectorAll('[data-feedback]').forEach(button=>button.addEventListener('click',()=>{feedback=button.dataset.feedback;render();toast('شكراً لملاحظتك. تم حفظها لهذه الجلسة فقط.');}));
  document.querySelector('[data-save-report]')?.addEventListener('click',()=>{const preview=new URLSearchParams(location.search).get('demo');const r=preview&&demoMode?normalizeVerification(fixture(preview),exampleTitle,true):result;if(!r)return;const id=`saved-${r.title}`;if(!savedNews.some(x=>x.id===id))savedNews.unshift({id,title:r.title,explanation:r.explanation,source_name:r.sources[0]?.name || '',source_url:r.sources[0]?.url,news_date:r.newsDate,match_score:r.confidenceScore,report:r});storage.set('saber:saved',savedNews);toast('تم حفظ الخبر لهذه الجلسة.');});
  document.querySelector('.toggle-password')?.addEventListener('click',event=>{const input=document.querySelector('[name=password]');input.type=input.type==='password'?'text':'password';event.currentTarget.setAttribute('aria-label',input.type==='password'?'إظهار كلمة المرور':'إخفاء كلمة المرور');});
  document.querySelectorAll('[data-unavailable]').forEach(button=>button.addEventListener('click',()=>toast('خدمة الحسابات غير متصلة بعد. يمكنك التحقق من الأخبار دون تسجيل دخول.')));
  document.querySelector('[data-terms]')?.addEventListener('click',()=>toast('سيتم توفير الشروط وسياسة الخصوصية عند تفعيل خدمة الحسابات.'));
  const auth=document.querySelector('#auth-form');
  auth?.querySelector('[name=password]')?.addEventListener('input',event=>{const value=event.target.value;const rules={length:value.length>=8,case:/[a-z]/.test(value)&&/[A-Z]/.test(value),number:/\d/.test(value)};for(const [key,met]of Object.entries(rules))document.querySelector(`[data-rule=${key}]`)?.classList.toggle('met',met);});
  auth?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const message=document.querySelector('#auth-message');if(form.confirm && form.confirm.value!==form.password.value){message.textContent='كلمتا المرور غير متطابقتين.';return;}if(form.confirm && !(/(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}/.test(form.password.value))){message.textContent='يرجى استيفاء جميع متطلبات كلمة المرور.';return;}message.textContent='خدمة الحسابات غير متصلة بعد. لم يتم إرسال بياناتك أو إنشاء جلسة دخول.';});
}
document.addEventListener('click',event=>{const link=event.target.closest('a');if(!link||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey||event.button!==0||link.target==='_blank')return;const url=new URL(link.href);if(url.origin!==location.origin)return;event.preventDefault();navigate(url.pathname+url.search+url.hash);});
window.addEventListener('popstate',render);
render();
